# Generated by Django 2.0.4 on 2018-05-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20180508_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
