# Generated by Django 2.0.4 on 2018-06-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_imageset_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident1', models.CharField(db_index=True, max_length=200)),
                ('ident2', models.CharField(db_index=True, max_length=200)),
                ('matrix', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='imageset',
            name='ident',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
