# Generated by Django 2.0.4 on 2018-06-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20180605_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignment',
            name='type',
            field=models.CharField(db_index=True, default='user', max_length=10),
        ),
    ]
