# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hsm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hsm.proto',
  package='hsm',
  syntax='proto3',
  serialized_pb=_b('\n\thsm.proto\x12\x03hsm\"(\n\x05Vec3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"3\n\x05Vec4D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\"*\n\x04\x46\x61\x63\x65\x12\n\n\x02v1\x18\x01 \x01(\r\x12\n\n\x02v2\x18\x02 \x01(\r\x12\n\n\x02v3\x18\x03 \x01(\r\"n\n\x04Mesh\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x1c\n\x08vertices\x18\x64 \x03(\x0b\x32\n.hsm.Vec3D\x12\x18\n\x05\x66\x61\x63\x65s\x18\x65 \x03(\x0b\x32\t.hsm.Face\x12\x1b\n\x07normals\x18\x66 \x03(\x0b\x32\n.hsm.Vec3D\"9\n\tImageInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x65xt\x18\x02 \x01(\t\x12\x11\n\tbyte_size\x18\x03 \x01(\r\"\xc4\x01\n\nAPIRequest\x12\x11\n\tclient_id\x18\x01 \x01(\r\x12/\n\x0b\x63lient_type\x18\x02 \x01(\x0e\x32\x1a.hsm.APIRequest.ClientType\x12\x17\n\x04mesh\x18\x64 \x01(\x0b\x32\t.hsm.Mesh\x12#\n\nimage_info\x18\xc8\x01 \x01(\x0b\x32\x0e.hsm.ImageInfo\"4\n\nClientType\x12\r\n\tUNIVERSAL\x10\x00\x12\t\n\x05IMAGE\x10\x01\x12\x0c\n\x08HOLOLENS\x10\x02\")\n\x0b\x41PIResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\tb\x06proto3')
)



_APIREQUEST_CLIENTTYPE = _descriptor.EnumDescriptor(
  name='ClientType',
  full_name='hsm.APIRequest.ClientType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNIVERSAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMAGE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOLOLENS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=473,
  serialized_end=525,
)
_sym_db.RegisterEnumDescriptor(_APIREQUEST_CLIENTTYPE)


_VEC3D = _descriptor.Descriptor(
  name='Vec3D',
  full_name='hsm.Vec3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='hsm.Vec3D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='hsm.Vec3D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='hsm.Vec3D.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=58,
)


_VEC4D = _descriptor.Descriptor(
  name='Vec4D',
  full_name='hsm.Vec4D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='hsm.Vec4D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='hsm.Vec4D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='hsm.Vec4D.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='hsm.Vec4D.w', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=111,
)


_FACE = _descriptor.Descriptor(
  name='Face',
  full_name='hsm.Face',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v1', full_name='hsm.Face.v1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v2', full_name='hsm.Face.v2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v3', full_name='hsm.Face.v3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=155,
)


_MESH = _descriptor.Descriptor(
  name='Mesh',
  full_name='hsm.Mesh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='hsm.Mesh.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertices', full_name='hsm.Mesh.vertices', index=1,
      number=100, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='faces', full_name='hsm.Mesh.faces', index=2,
      number=101, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normals', full_name='hsm.Mesh.normals', index=3,
      number=102, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=267,
)


_IMAGEINFO = _descriptor.Descriptor(
  name='ImageInfo',
  full_name='hsm.ImageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hsm.ImageInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ext', full_name='hsm.ImageInfo.ext', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='byte_size', full_name='hsm.ImageInfo.byte_size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=326,
)


_APIREQUEST = _descriptor.Descriptor(
  name='APIRequest',
  full_name='hsm.APIRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='hsm.APIRequest.client_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_type', full_name='hsm.APIRequest.client_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mesh', full_name='hsm.APIRequest.mesh', index=2,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_info', full_name='hsm.APIRequest.image_info', index=3,
      number=200, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _APIREQUEST_CLIENTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=525,
)


_APIRESPONSE = _descriptor.Descriptor(
  name='APIResponse',
  full_name='hsm.APIResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='hsm.APIResponse.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='hsm.APIResponse.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=568,
)

_MESH.fields_by_name['vertices'].message_type = _VEC3D
_MESH.fields_by_name['faces'].message_type = _FACE
_MESH.fields_by_name['normals'].message_type = _VEC3D
_APIREQUEST.fields_by_name['client_type'].enum_type = _APIREQUEST_CLIENTTYPE
_APIREQUEST.fields_by_name['mesh'].message_type = _MESH
_APIREQUEST.fields_by_name['image_info'].message_type = _IMAGEINFO
_APIREQUEST_CLIENTTYPE.containing_type = _APIREQUEST
DESCRIPTOR.message_types_by_name['Vec3D'] = _VEC3D
DESCRIPTOR.message_types_by_name['Vec4D'] = _VEC4D
DESCRIPTOR.message_types_by_name['Face'] = _FACE
DESCRIPTOR.message_types_by_name['Mesh'] = _MESH
DESCRIPTOR.message_types_by_name['ImageInfo'] = _IMAGEINFO
DESCRIPTOR.message_types_by_name['APIRequest'] = _APIREQUEST
DESCRIPTOR.message_types_by_name['APIResponse'] = _APIRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vec3D = _reflection.GeneratedProtocolMessageType('Vec3D', (_message.Message,), dict(
  DESCRIPTOR = _VEC3D,
  __module__ = 'hsm_pb2'
  # @@protoc_insertion_point(class_scope:hsm.Vec3D)
  ))
_sym_db.RegisterMessage(Vec3D)

Vec4D = _reflection.GeneratedProtocolMessageType('Vec4D', (_message.Message,), dict(
  DESCRIPTOR = _VEC4D,
  __module__ = 'hsm_pb2'
  # @@protoc_insertion_point(class_scope:hsm.Vec4D)
  ))
_sym_db.RegisterMessage(Vec4D)

Face = _reflection.GeneratedProtocolMessageType('Face', (_message.Message,), dict(
  DESCRIPTOR = _FACE,
  __module__ = 'hsm_pb2'
  # @@protoc_insertion_point(class_scope:hsm.Face)
  ))
_sym_db.RegisterMessage(Face)

Mesh = _reflection.GeneratedProtocolMessageType('Mesh', (_message.Message,), dict(
  DESCRIPTOR = _MESH,
  __module__ = 'hsm_pb2'
  # @@protoc_insertion_point(class_scope:hsm.Mesh)
  ))
_sym_db.RegisterMessage(Mesh)

ImageInfo = _reflection.GeneratedProtocolMessageType('ImageInfo', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEINFO,
  __module__ = 'hsm_pb2'
  # @@protoc_insertion_point(class_scope:hsm.ImageInfo)
  ))
_sym_db.RegisterMessage(ImageInfo)

APIRequest = _reflection.GeneratedProtocolMessageType('APIRequest', (_message.Message,), dict(
  DESCRIPTOR = _APIREQUEST,
  __module__ = 'hsm_pb2'
  # @@protoc_insertion_point(class_scope:hsm.APIRequest)
  ))
_sym_db.RegisterMessage(APIRequest)

APIResponse = _reflection.GeneratedProtocolMessageType('APIResponse', (_message.Message,), dict(
  DESCRIPTOR = _APIRESPONSE,
  __module__ = 'hsm_pb2'
  # @@protoc_insertion_point(class_scope:hsm.APIResponse)
  ))
_sym_db.RegisterMessage(APIResponse)


# @@protoc_insertion_point(module_scope)
